### ISSUE TITLE
Allow findings to be ignored

### ISSUE THREAD

**Issue by jamestelfer** [cultureamp/ecr-scan-results-buildkite-plugin#24]
Given configuration, allow a finding to be ignored, as identified by name.

A finding ignore configuration can set an expiry date, and a reason for the entry.

Ignore configuration can be specified in the repository, or centrally on the agent in the home directory of the agent user.

Configuration is YAML:

```yaml
ignores:
  # simple entries with ID only
  - CVE-2020-123
  - CVE-2021-321
  # expiry and reason can be specified using object notation
  - id: CVE-2023-456
    until: 2023-12-31
    reason: giving it time to be patched upstream
```

Configuration order:

1. `/etc/ecr-scan-results-buildkite-plugin/ignore.y[a]ml`
2. `.ecr-scan-results-ignore.y[a]ml`

(first present of the `.yaml` or `.yml` extension).

Configuration is merged such that entries from the repository override entries on the agent, when matched on ID.

"Ignore" means that the CVE will not count towards thresholds. **It will still be shown in the report.** Ignored entries in the list of findings will be muted in their display, and annotated "_(ignored)_".

If a finding is ignored, the top level count will indicate this, for example "5 Critical (+ 2 ignored)".
